import Head from 'next/head'
import Register from './register';
import { firestore } from '../firebase/init'

export default function Home({ data }) {

  if (!data) {
    return <h1>Oeps</h1>
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Register categories={data}></Register>
      </main>
    </div>
  )
}

export async function getServerSideProps(context) {
  let data = {}

  const cityRef = firestore.collection('categories').doc('types');
  const doc = await cityRef.get();
  if (!doc.exists) {
    return {
      notFound: true,
    }
  } else {
    data = doc.data();
  }
  return {
    props: { data }, // will be passed to the page component as props
  }
}