import Head from 'next/head'
import Register from './register';


export default function Home({ data }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Register categories={data}></Register>
      </main>
    </div>
  )
}

export async function getStaticProps(context) {

  const response = await fetch('http://localhost:3000/api/register');
  const data = await response.json();


  if (!data) {
    return {
      redirect: {
        destination: 'google.com',

      }
    }
  }

  return {
    props: { data }, // will be passed to the page component as props
  }
}